<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PHydro-cover-small.png">
*This is the Jupyter notebook version of the [Python in Hydrology](http://www.greenteapress.com/pythonhydro/pythonhydro.html) by Sat Kumar Tomer.*
*Source code is available at [code.google.com](https://code.google.com/archive/p/python-in-hydrology/source).*

*The book is available under the [GNU Free Documentation License](http://www.gnu.org/copyleft/fdl.html). If you have comments, corrections or suggestions, please send email to satkumartomer@gmail.com.*

<!--NAVIGATION-->
< [Useful Attributes and Methods](03.02-Useful-Attributes-and-Methods.ipynb) | [Contents](Index.ipynb) | [Array Manipulation](03.04-Array-Manipulation.ipynb) >

## 3.3 索引

在本节中，我们将讨论如何引用`numpy`数组中的一些元素。请记住，Python中的第一个索引为0。我们会生成一些数组，例如某个数组序列[0，1，...,9]的元素的3次方。

In [16]:
import numpy as np
foo = np.arange(10)**3
foo

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

打印数组中的第三项。第三项意味着我们需要把索引设为2。

In [17]:
foo[2]

8

假设，我们想要打印一些数组序列，例如2,3和4的索引。

In [18]:
foo[2:5]

array([ 8, 27, 64], dtype=int32)

我们使用`2:5`获取2,3和4的索引值。这与`foo[np.arrange(2,5,1)]`相同。当我们没有在数组的索引中指定第三个值，默认情况下取1。如果我们要打印2到8的数值，间距为3。现在因为间距不是1，所以我们需要来定义它。

In [19]:
foo[2:10:3]

array([  8, 125, 512], dtype=int32)

如果我们将索引中的第一个条目留空，例如将数组元素作为数组的开头，间距为2，最大为6，则发出如下指令: