<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PHydro-cover-small.png">
*This is the Jupyter notebook version of the [Python in Hydrology](http://www.greenteapress.com/pythonhydro/pythonhydro.html) by Sat Kumar Tomer.*
*Source code is available at [code.google.com](https://code.google.com/archive/p/python-in-hydrology/source).*

*The book is available under the [GNU Free Documentation License](http://www.gnu.org/copyleft/fdl.html). If you have comments, corrections or suggestions, please send email to satkumartomer@gmail.com.*

<!--NAVIGATION-->
< [3. Array](03.00-Array.ipynb) | [Contents](Index.ipynb) | [Useful Attributes and Methods](03.02-Useful-Attributes-and-Methods.ipynb) >

## 3.1生成连续数组

通常我们需要向量遵循简单的顺序，例如，包含元素[10,11,12,13]或[5,10,15,20]或[1.0,1.2,1.4,1.6,1.8,2.0]的向量。我们看到，在这些向量中，元素遵循一些简单的顺序，所以如果有简单的方法来定义这些向量就更好了。一些创建这些向量的方法如下：

### 3.1.1 linspace

如果我们对生成向量感兴趣，向量的元素有着统一间距，知道上下限以及元素数量，那么这种情况下`linspace`是首要的选择:

In [1]:
import numpy as np
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

因为`linspace`位于`numpy`库中，所以我们首先需要导入`numpy`库，并给它一个缩写名。之后我们调用`linspace`用下限、上限和要生成的元素数量。在这个例子中，0是下限，2是上限，9是元素个数。让我们生成更多的向量以更好的理解这个函数，这次我们以0为下限，2π为上限，元素个数设为100.

In [3]:
x = np.linspace(0,2*np.pi,100)

元素个数默认为50，所以如果我们没有指定元素个数，那么我们会得到50个等间距的元素。我们可以使用`len`函数获得任意数组的长度。

In [4]:
foo = np.linspace(0,1)
len(foo)

50

### 3.1.2 arange

再假设我们想要生成一个有着统一元素间距的向量，但这次我们不知道具体的元素数量，我们只是知道元素间的增量(间距)。在这种情况下，`arrange`可以被使用。`arrange`同样需要上下限。在接下来的例子中，我们将要生成的向量下限10，上限为30，增量为30。所以从`linspace`中得来的知识，我们可以这么做：

In [5]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

哦！发生了什么？为什么Python没有打印30。因为`arrange`函数不包含元素中的第二个参数。所以我们想要打印到30，我们会这样做。

In [6]:
np.arange( 10, 31, 5 )

array([10, 15, 20, 25, 30])

这次我们得到了需要的输出。`arrange`同样可以取浮点数增量。让我们生成一个下限为0，上限为2，增量为0.3的向量。

In [7]:
np.arange( 0, 2, 0.3 ) # 接受浮点参数

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

### 3.1.3 zeros

`zeros`函数在我们要生成的向量所有元素都为0时使用。

In [8]:
foo = np.zeros(5)
foo

array([ 0.,  0.,  0.,  0.,  0.])

### 3.1.4 ones

`ones`函数在向量中所有元素均为1时使用。让我们说，我们想要生成一个变量包含了的所有元素为1，并且维度为`3×2`。

In [9]:
foo = np.ones((3,2))
foo

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

记住，如果维度超过1，那么维度将以`tuple`的形式呈现。

### 3.1.5 empty

`empty`在初始化变量时非常有用。这将无用的数据分配给稍后要修改的元素。

In [10]:
foo = np.empty((2,5))
foo

array([[  6.11020233e-313,   6.11020232e-313,   6.11020237e-313,
          6.11020239e-313,   6.11020239e-313],
       [  6.11020237e-313,   6.11020240e-313,   6.11020233e-313,
          6.11020240e-313,   6.11020240e-313]])

除了`zeros`,`ones`,`empty`，数据类型（例如，`int`,`float`等）同样可以被定义。

In [11]:
foo = np.empty((2,5),int)
foo

array([[1778384997,   56885249,     156928, 1509950083,   56950787],
       [  40108288,   16798464, 1392509540, -978695392,         28]])

你可以看到`foo`中所有元素是整型，即便数值是无用的。

### 3.1.6 rand

`rand`用于生成0和1之间均匀分布的随机变量。

In [12]:
foo = np.random.rand(3,2)
foo

array([[ 0.31926042,  0.88777405],
       [ 0.03734307,  0.4816187 ],
       [ 0.72920331,  0.85784028]])

### randn

`randn`用来生成具有正态分布的随机变量，其均值为0，方差为1。

In [13]:
foo = np.random.randn(2,4)
foo

array([[-0.87325251, -0.80658988,  0.93298161,  1.26130384],
       [ 1.04079985,  1.41569764, -0.51769584,  0.12887116]])