<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PHydro-cover-small.png">
*This is the Jupyter notebook version of the [Python in Hydrology](http://www.greenteapress.com/pythonhydro/pythonhydro.html) by Sat Kumar Tomer.*
*Source code is available at [code.google.com](https://code.google.com/archive/p/python-in-hydrology/source).*

*The book is available under the [GNU Free Documentation License](http://www.gnu.org/copyleft/fdl.html). If you have comments, corrections or suggestions, please send email to satkumartomer@gmail.com.*

<!--NAVIGATION-->
< [Generating Sequential Arrays](03.01-Generating-Sequential-Arrays.ipynb) | [Contents](Index.ipynb) | [Indexing](03.03-Indexing.ipynb) >

## 3.2 有用的属性和方法

`ndarray`(采用`numpy`生成数组)提供了属性用于快速执行常用属性。这些属性是用来快速获得`ndarray`性能。让我们首先生成一些元素是正态分布随机数的向量，然后尝试这些属性。在这里我使用正态分布随机变量来演示，但是这些属性可用于任何`numpy.array`。我们生成一个尺寸为5×100的二维向量。

In [2]:
import numpy as np
foo = np.random.randn(5,100)

让我们检查维数(不是数组的大小或形状)。维数意味着多少维度与数组相关联。例如，在数学术语中，向量有一个维度，矩阵有两个维度。

In [3]:
foo.ndim

2

数组的维度可以使用`shape`属性来访问。

In [4]:
foo.shape

(5, 100)

`size`属性提供了数组中元素的总数。这仅仅是`shape`属性给出的所有元素的乘法。

In [5]:
foo.size

500

数据类型（即float，integer等）是使用属性`dtype`提取的。

In [6]:
foo.dtype

dtype('float64')

这告诉我们，变量`foo`是浮点数，并且有64位。该变量的平均值或均值利用`mean`方法计算。

In [7]:
foo.mean()

-0.0041171555846341266

这提供了整个数组的均值(例如本例中的500个元素)。假设我们想要估计某个维度上的平均值，比如第2(1)维，那么在这种情况下，我们需要为`mean`提供额外的参数，例如`axis`。

In [8]:
foo.mean(axis=1)

array([-0.06387594,  0.16266965,  0.03012094, -0.13008651, -0.01941391])

使用`min`，`max`，`std`和`var`方法估计数组的最小值、最大值、标准差和方差。

In [9]:
# 获取最小值
foo.min()

-2.9695292746011144

In [10]:
# 获取最大值
foo.max()

3.2959540703899011

In [11]:
# 获取标准差
foo.std()

1.023395616516114

In [12]:
# 获取方差
foo.var()

1.0473385879043973

请记住，以`#`开头的行代表注释。注释使阅读和理解代码更容易。所以，碰到一些不容易从代码中轻易理解的事情，无论何时都要进行注释。

矩阵的迹表示对角元素的和，在方阵的情况下有意义。Python甚至在矩阵不为方时估计迹，并且迹通过使用`trace`属性来计算。

In [13]:
foo.trace()

0.86028845770255957

每个类都有许多属性，在探索与任何变量、类、库相关联的属性和方法时，`dir`函数是一个有用的工具。让我们看看我们的变量`foo`所具有的所有方法和属性。

```ipynb
# 获得变量foo的所有方法和属性的列表
In [14]:dir(foo)
Out [14]:['T', '__abs__', ............. 'flat', 'view']
```

`dir(foo)`的输出非常长，为简洁起见省略了。以`_`开头的属性/方法应该是私有属性，通常不需要。

## 3.2 索引

在本节中，我们将讨论如何引用`numpy`数组中的一些元素。请记住，Python中的第一个索引为0。我们会生成一些数组，例如某个数组序列[0，1，...,9]的元素的3次方。

In [16]:
import numpy as np
foo = np.arange(10)**3
foo

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

打印数组中的第三项。第三项意味着我们需要把索引设为2。

In [17]:
foo[2]

8

假设，我们想要打印一些数组序列，例如2,3和4的索引。

In [18]:
foo[2:5]

array([ 8, 27, 64], dtype=int32)

我们使用`2:5`获取2,3和4的索引值。这与`foo[np.arrange(2,5,1)]`相同。当我们没有在数组的索引中指定第三个值，默认情况下取1。如果我们要打印2到8的数值，间距为3。现在因为间距不是1，所以我们需要来定义它。

In [19]:
foo[2:10:3]

array([  8, 125, 512], dtype=int32)

如果我们将索引中的第一个条目留空，例如将数组元素作为数组的开头，间距为2，最大为6，则发出如下指令: